### ISSUE TITLE
using CommonAPI in multithreading scene

### ISSUE THREAD

**Issue by ReleaseBug** [Pelagicore/common-api-tools#1]
Hi，
I am a beginner of learning CommonAPI.

And i am working on an example FIDL:
HelloWorld FIDL:
  method say {
    in {
      String name
    }
    out {
      String message
    }
  }

I have some questions about this method.
void HelloWorldStubImpl::say(const std::shared_ptr<CommonAPI::ClientId> _client, std::string name, sayReply_t reply)

I want to use [say] method in a multithreading scene, There exist a working thread called BackGroundWorker.
When HelloWorldStubImpl::say() is called, HelloWorldStubImpl::say() will not [reply] imediately but just sent a message to BackGroundWorker.
BackGroundWorker will work on this message and do something.

Q1: Is [reply] thread safe?  can i call [reply] in BackGroundWorker's thread when BackGroundWorker has done its job?

Q2: Is there a better solution in this scene?

You may save my time if you can answer my questions.   Thx~

**Comment by GordanM** [comment]
@ReleaseBug unfortunately this repository is no longer maintained. I believe it would be better to refer to the upstream repository and tutorial:

* https://github.com/GENIVI/capicxx-core-tools
* https://at.projects.genivi.org/wiki/pages/viewpage.action?pageId=5472311

**Comment by ReleaseBug** [comment]
@GordanM Thank you very much.
